insert into public.disease_localizations
  (disease_id, language_tag, name, description, symptom_preview, causes, prevention, guidance, when_to_act, disclaimer)
values
  ('leaf-spot','en','Leaf Spot','Spots can affect eggplant leaves and may progress to stems or fruit.','Brown or black spots that may yellow, dry, or tear.','Often associated with fungal or bacterial pathogens and prolonged leaf wetness.','Improve airflow, space plants, water near soil, and clean tools.','Isolate badly affected material and ask an agricultural specialist to confirm the cause before choosing a control.','Act when spots spread quickly, leaves drop, or stems and fruit develop lesions.','Screening aid only; similar symptoms can have different causes. Consult a qualified agricultural specialist before treatment.'),
  ('leaf-spot','fil','Leaf Spot','Maaaring maapektuhan ang dahon at kumalat sa tangkay o bunga.','Kayumanggi o itim na batik na maaaring manilaw, matuyo, o mapunit.','Madalas kaugnay ng fungal o bacterial pathogens at matagal na pagkabasa ng dahon.','Pagandahin ang airflow, pagitan ng tanim, pagdidilig sa lupa, at kalinisan ng kagamitan.','Ihiwalay ang malubhang apektadong bahagi at ipakumpirma ang sanhi sa agricultural specialist.','Kumilos kapag mabilis dumami ang batik, nalalagas ang dahon, o may sugat sa tangkay at bunga.','Pantulong lamang sa paunang pagsusuri; maaaring magkapareho ang sintomas ng magkaibang sanhi. Kumonsulta muna sa espesyalista.'),
  ('mosaic-virus','en','Mosaic Virus','Virus-like symptoms can distort leaves and reduce growth.','Yellow-green mosaic patterns with curled or distorted growth.','Plant viruses may spread through infected seed, plant material, tools, or insect vectors.','Use clean seed and tools, manage vectors, and avoid propagating suspicious plants.','Isolate suspicious plants and sanitize hands and tools; no treatment removes a virus from an infected plant.','Act promptly when mosaic patterns and distorted new growth appear across plants.','Screening aid only; laboratory or specialist confirmation is needed for a virus diagnosis.'),
  ('mosaic-virus','fil','Mosaic Virus','Maaaring baluktutin ng virus-like symptoms ang dahon at pahinain ang paglaki.','Dilaw-berdeng mosaic pattern at kulot o baluktot na tubo.','Maaaring kumalat ang plant virus sa kontaminadong binhi, halaman, kagamitan, o insect vector.','Gumamit ng malinis na binhi at kagamitan, bantayan ang vector, at huwag paramihin ang kahina-hinalang halaman.','Ihiwalay ang halaman at linisin ang kamay at kagamitan; walang lunas na nag-aalis ng virus sa apektadong halaman.','Kumilos agad kapag may mosaic pattern at baluktot na bagong tubo sa maraming halaman.','Pantulong lamang sa screening; kailangan ang laboratoryo o espesyalista para makumpirma ang virus.'),
  ('white-molds','en','White Molds','Cottony growth may occur on stems, leaves, or fruit.','White cotton-like growth, soft tissue, wilting, or black sclerotia.','Commonly associated with Sclerotinia favored by cool, humid, wet, or crowded conditions.','Reduce moisture, improve airflow, and avoid casually composting infected material.','Remove and isolate affected plants without spreading black sclerotia.','Act immediately when cottony growth, soft rot, sudden wilt, or sclerotia appear.','Screening aid only; confirm the organism before applying a fungicide or other treatment.'),
  ('white-molds','fil','Puting Amag','Maaaring lumitaw ang tila bulak na amag sa tangkay, dahon, o bunga.','Puting tila bulak, malambot na tisyu, pagkalanta, o itim na sclerotia.','Karaniwang kaugnay ng Sclerotinia na lumalala sa malamig, mahalumigmig, basa, o siksik na tanim.','Bawasan ang moisture, pagandahin ang airflow, at huwag basta i-compost ang apektadong materyal.','Alisin at ibukod ang apektadong halaman nang hindi ikinakalat ang itim na sclerotia.','Kumilos agad kapag may tila bulak, soft rot, biglang wilt, o sclerotia.','Pantulong lamang sa screening; ipakumpirma ang organism bago gumamit ng fungicide o ibang treatment.'),
  ('wilt','en','Wilt','Leaves droop, yellow, and may remain dry on weakened plants.','Persistent drooping, yellow lower leaves, and weak stems.','Possible causes include Verticillium, root rot, root injury, or water stress.','Avoid waterlogging and moving soil from affected beds; use clean growing material.','Check soil moisture and roots, isolate affected plants, and seek specialist confirmation.','Act when correct watering does not restore the plant or wilting spreads.','Screening aid only; several root, vascular, and water problems look alike.'),
  ('wilt','fil','Pagkalanta','Yumuyuko at naninilaw ang dahon at maaaring manatiling tuyo sa mahinang halaman.','Patuloy na pagyuko, dilaw na ibabang dahon, at mahinang tangkay.','Maaaring Verticillium, root rot, pinsala sa ugat, o problema sa tubig.','Iwasan ang waterlogging at paglipat ng lupa mula sa apektadong tanim; gumamit ng malinis na materyal.','Suriin ang moisture at ugat, ihiwalay ang halaman, at ipakumpirma sa espesyalista.','Kumilos kapag hindi bumabalik ang sigla matapos ang tamang pagdidilig o kumakalat ang pagkalanta.','Pantulong lamang sa screening; magkakahawig ang ilang problema sa ugat, vascular tissue, at tubig.'),
  ('insect-pest','en','Insect Pest','Chewing or sap-feeding insects can damage eggplant leaves, shoots, stems, or fruit.','Irregular holes, chewed edges, insects, eggs, or feeding scars.','Different insects and life stages cause similar visible damage.','Inspect plants often, keep the area clean, and protect beneficial insects.','Inspect both leaf surfaces, shoots, stems, and fruit and photograph the pest for identification.','Act when damage spreads quickly, new growth or fruit is affected, or plants wilt.','Screening aid only; identify the exact pest before choosing a pesticide.'),
  ('insect-pest','fil','Pesteng Insekto','Maaaring sirain ng ngumunguya o sumisipsip na insekto ang dahon, usbong, tangkay, o bunga.','Hindi pantay na butas, nguyang gilid, insekto, itlog, o feeding scars.','Magkakahawig ang pinsala ng iba’t ibang insekto at yugto nito.','Regular na inspeksyunin, panatilihing malinis ang paligid, at protektahan ang beneficial insects.','Suriin ang magkabilang panig ng dahon, usbong, tangkay, at bunga at kunan ng malinaw na larawan ang peste.','Kumilos kapag mabilis dumami ang pinsala, apektado ang bagong tubo o bunga, o nalalanta ang halaman.','Pantulong lamang sa screening; tukuyin muna ang eksaktong peste bago pumili ng pestisidyo.'),
  ('melon-thrips','en','Melon Thrips','Tiny thrips can scar and deform eggplant leaves and fruit.','Silvery or bronze areas, curled growth, and tiny insects underneath leaves.','Thrips palmi feeds on foliage and blossoms and may transmit some plant viruses.','Monitor young growth, manage weeds, and conserve beneficial insects.','Use magnification to inspect leaf undersides and shoots; seek advice before insecticide use.','Act when thrips are numerous or bronzing, scarring, and deformation worsen quickly.','Screening aid only; microscopic or specialist confirmation may be needed.'),
  ('melon-thrips','fil','Melon Thrips','Maaaring peklatin at baluktutin ng maliliit na thrips ang dahon at bunga.','Pilak o bronze na bahagi, kulot na tubo, at maliit na insekto sa ilalim ng dahon.','Sumisipsip ang Thrips palmi sa dahon at bulaklak at maaaring magdala ng ilang plant virus.','Bantayan ang batang tubo, kontrolin ang damo, at protektahan ang beneficial insects.','Gumamit ng magnification sa ilalim ng dahon at usbong; kumonsulta bago gumamit ng insecticide.','Kumilos kapag marami ang thrips o mabilis lumalala ang bronzing, scarring, at deformity.','Pantulong lamang sa screening; maaaring kailangan ang microscope o specialist confirmation.'),
  ('fruit-rot','en','Fruit Rot','Soft, dark, or sunken decay can expand across eggplant fruit.','Soft dark patches, sunken tissue, water-soaked lesions, or mold.','Fungal or oomycete diseases can worsen after injury, wetness, contamination, or poor airflow.','Keep fruit off wet soil, handle gently, keep tools clean, and improve airflow.','Separate affected fruit and keep it away from harvest and casual compost.','Act immediately when lesions expand quickly, mold or odor develops, or several fruit are affected.','Screening aid only; confirm the cause before applying a crop treatment.'),
  ('fruit-rot','fil','Pagkabulok ng Bunga','Maaaring kumalat sa bunga ang malambot, maitim, o lumulubog na pagkabulok.','Malambot na maitim na bahagi, lubog na tisyu, basang sugat, o amag.','Maaaring lumala ang fungal o oomycete disease dahil sa sugat, basa, kontaminasyon, o mahinang airflow.','Ilayo ang bunga sa basang lupa, hawakan nang maingat, linisin ang kagamitan, at pagandahin ang airflow.','Ihiwalay ang apektadong bunga at ilayo sa ani at karaniwang compost.','Kumilos agad kapag mabilis lumalaki ang sugat, may amag o amoy, o maraming bunga ang apektado.','Pantulong lamang sa screening; ipakumpirma ang sanhi bago gumamit ng treatment.'),
  ('fruit-borer','en','Fruit Borer','Larvae tunnel into eggplant shoots or fruit and feed inside.','Entry holes, frass around openings, wilted shoots, and internal feeding damage.','Eggplant fruit and shoot borer larvae remain hidden after tunneling into plant tissue.','Inspect frequently, maintain sanitation, and use integrated pest management.','Remove and safely dispose of tunneled shoots and fruit; seek locally appropriate IPM advice.','Act when fresh holes, frass, wilted shoots, or repeated fruit damage appear.','Screening aid only; verify the insect and follow local pesticide regulations and labels.'),
  ('fruit-borer','fil','Fruit Borer','Bumubutas ang larva sa usbong o bunga at kumakain sa loob.','Butas na pasukan, dumi sa paligid, nalantang usbong, at pinsala sa loob.','Nagtatago ang eggplant fruit and shoot borer larva matapos bumutas sa tissue.','Madalas na inspeksyunin, panatilihin ang sanitation, at gumamit ng integrated pest management.','Alisin at ligtas na itapon ang binutas na usbong at bunga; humingi ng angkop na lokal na IPM advice.','Kumilos kapag may sariwang butas, frass, nalantang usbong, o paulit-ulit na sira sa bunga.','Pantulong lamang sa screening; tukuyin ang insekto at sundin ang lokal na regulasyon at pesticide label.')
on conflict (disease_id, language_tag) do update set
  name=excluded.name, description=excluded.description, symptom_preview=excluded.symptom_preview,
  causes=excluded.causes, prevention=excluded.prevention, guidance=excluded.guidance,
  when_to_act=excluded.when_to_act, disclaimer=excluded.disclaimer, updated_at=now();

insert into public.disease_signs (disease_id, language_tag, position, text) values
  ('leaf-spot','en',0,'Circular brown or black spots'),('leaf-spot','en',1,'Yellow tissue around spots'),('leaf-spot','en',2,'Dry or brittle centers'),
  ('leaf-spot','fil',0,'Bilog na kayumanggi o itim na batik'),('leaf-spot','fil',1,'Dilaw na tissue sa paligid'),('leaf-spot','fil',2,'Tuyo o marupok na gitna'),
  ('mosaic-virus','en',0,'Mottled yellow-green color'),('mosaic-virus','en',1,'Distorted or curled leaves'),('mosaic-virus','en',2,'Reduced growth'),
  ('mosaic-virus','fil',0,'Halo-halong dilaw at berde'),('mosaic-virus','fil',1,'Baluktot o kulot na dahon'),('mosaic-virus','fil',2,'Mahinang paglaki'),
  ('white-molds','en',0,'White cotton-like growth'),('white-molds','en',1,'Soft affected tissue'),('white-molds','en',2,'Black resting structures'),
  ('white-molds','fil',0,'Puting tila bulak'),('white-molds','fil',1,'Malambot na apektadong bahagi'),('white-molds','fil',2,'Itim na resting structures'),
  ('wilt','en',0,'Persistent drooping'),('wilt','en',1,'Yellow lower leaves'),('wilt','en',2,'Weak stems or vascular browning'),
  ('wilt','fil',0,'Patuloy na pagyuko'),('wilt','fil',1,'Dilaw na ibabang dahon'),('wilt','fil',2,'Mahinang tangkay o brown vascular tissue'),
  ('insect-pest','en',0,'Irregular holes'),('insect-pest','en',1,'Chewed edges'),('insect-pest','en',2,'Visible insects or eggs'),
  ('insect-pest','fil',0,'Hindi pantay na butas'),('insect-pest','fil',1,'Nguyang gilid'),('insect-pest','fil',2,'Nakikitang insekto o itlog'),
  ('melon-thrips','en',0,'Silvery or bronze feeding scars'),('melon-thrips','en',1,'Crinkled young leaves'),('melon-thrips','en',2,'Tiny insects underneath leaves'),
  ('melon-thrips','fil',0,'Pilak o bronze na feeding scars'),('melon-thrips','fil',1,'Kulubot na batang dahon'),('melon-thrips','fil',2,'Maliit na insekto sa ilalim ng dahon'),
  ('fruit-rot','en',0,'Soft dark patches'),('fruit-rot','en',1,'Sunken or water-soaked tissue'),('fruit-rot','en',2,'Rapidly enlarging decay'),
  ('fruit-rot','fil',0,'Malambot na maitim na bahagi'),('fruit-rot','fil',1,'Lubog o basang tissue'),('fruit-rot','fil',2,'Mabilis lumaking pagkabulok'),
  ('fruit-borer','en',0,'Entry holes'),('fruit-borer','en',1,'Frass around openings'),('fruit-borer','en',2,'Internal feeding damage'),
  ('fruit-borer','fil',0,'Butas na pasukan'),('fruit-borer','fil',1,'Dumi sa paligid ng butas'),('fruit-borer','fil',2,'Pinsala sa loob ng bunga')
on conflict (disease_id, language_tag, position) do update set text=excluded.text;

insert into public.disease_references (disease_id, language_tag, position, publisher, title, url) values
  ('leaf-spot','en',0,'University of Minnesota Extension','Eggplant disease diagnosis','https://apps.extension.umn.edu/garden/diagnose/plant/vegetable/eggplant/stemdiscolored.html'),
  ('leaf-spot','fil',0,'University of Minnesota Extension','Eggplant disease diagnosis','https://apps.extension.umn.edu/garden/diagnose/plant/vegetable/eggplant/stemdiscolored.html'),
  ('mosaic-virus','en',0,'UC Statewide IPM','Eggplant Pest Management Guidelines','https://ipm.ucanr.edu/agriculture/eggplant/'),('mosaic-virus','fil',0,'UC Statewide IPM','Eggplant Pest Management Guidelines','https://ipm.ucanr.edu/agriculture/eggplant/'),
  ('white-molds','en',0,'University of Minnesota Extension','Eggplant disease diagnosis','https://apps.extension.umn.edu/garden/diagnose/plant/vegetable/eggplant/stemdiscolored.html'),('white-molds','fil',0,'University of Minnesota Extension','Eggplant disease diagnosis','https://apps.extension.umn.edu/garden/diagnose/plant/vegetable/eggplant/stemdiscolored.html'),
  ('wilt','en',0,'UC Statewide IPM','Verticillium Wilt / Eggplant','https://ipm.ucanr.edu/agriculture/eggplant/verticillium-wilt/'),('wilt','fil',0,'UC Statewide IPM','Verticillium Wilt / Eggplant','https://ipm.ucanr.edu/agriculture/eggplant/verticillium-wilt/'),
  ('insect-pest','en',0,'UC Statewide IPM','Eggplant Pest Management Guidelines','https://ipm.ucanr.edu/agriculture/eggplant/'),('insect-pest','fil',0,'UC Statewide IPM','Eggplant Pest Management Guidelines','https://ipm.ucanr.edu/agriculture/eggplant/'),
  ('melon-thrips','en',0,'University of Florida IFAS','Melon Thrips','https://edis.ifas.ufl.edu/publication/IN292'),('melon-thrips','fil',0,'University of Florida IFAS','Melon Thrips','https://edis.ifas.ufl.edu/publication/IN292'),
  ('fruit-rot','en',0,'University of Minnesota Extension','Eggplant disease diagnosis','https://apps.extension.umn.edu/garden/diagnose/plant/vegetable/eggplant/stemdiscolored.html'),('fruit-rot','fil',0,'University of Minnesota Extension','Eggplant disease diagnosis','https://apps.extension.umn.edu/garden/diagnose/plant/vegetable/eggplant/stemdiscolored.html'),
  ('fruit-borer','en',0,'Philippine Department of Agriculture','Eggplant Fruit and Shoot Borer','https://rfo12.da.gov.ph/?p=5012'),('fruit-borer','fil',0,'Philippine Department of Agriculture','Eggplant Fruit and Shoot Borer','https://rfo12.da.gov.ph/?p=5012')
on conflict (disease_id, language_tag, position) do update set publisher=excluded.publisher,title=excluded.title,url=excluded.url;
